### ISSUE TITLE
Add font smoothing

### ISSUE THREAD

**Issue by pdhoopr** [hoopr/codework#50]
We should add font smoothing and see if we like how it looks. This would involve adding the following to `global.css`:

```css
body {
  -moz-osx-font-smoothing: grayscale;
  -webkit-font-smoothing: antialiased;
  text-rendering: optimizeLegibility;
  text-size-adjust: 100%;
}
```

We should also find all the font weight 300s and get rid of them if we go with this. It makes them too thin.
